name: ubuntu-desktop
services:
  ubuntu:
    build: ubuntu
    ports:
      - 8080
    labels:
      app: gui
    
endpoints:
  ubuntu:
   - path: /
     service: ubuntu
     port: 8080
volumes:
  tmp: